/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATable: typeof import('ant-design-vue/es')['Table']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CourseSource: typeof import('./../components/user/source/CourseSource.vue')['default']
    CourseType: typeof import('./../components/user/source/CourseType.vue')['default']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    EchartsContainer: typeof import('./../components/index/EchartsContainer.vue')['default']
    LockFilled: typeof import('@ant-design/icons-vue')['LockFilled']
    LogoTop: typeof import('./../components/LogoTop.vue')['default']
    NotificationOutlined: typeof import('@ant-design/icons-vue')['NotificationOutlined']
    PageTitle: typeof import('./../components/PageTitle.vue')['default']
    PracticeCommunity: typeof import('./../components/user/source/PracticeCommunity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
    StepA: typeof import('./../components/user/survey/StepA.vue')['default']
    StepB: typeof import('./../components/user/survey/StepB.vue')['default']
    StepC: typeof import('./../components/user/survey/StepC.vue')['default']
    StepD: typeof import('./../components/user/survey/StepD.vue')['default']
    StepE: typeof import('./../components/user/survey/StepE.vue')['default']
    UploadOutlined: typeof import('@ant-design/icons-vue')['UploadOutlined']
    UserLogin: typeof import('./../components/Login/UserLogin.vue')['default']
    UserReg: typeof import('./../components/Login/UserReg.vue')['default']
  }
}
